# Generated by Django 5.2.4 on 2026-02-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['category', '-votes']},
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('scratch', 'Scratch'), ('app_inventor', 'App Inventor'), ('robotics', 'Robotics')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app_inventor_votes', models.ManyToManyField(blank=True, related_name='app_inventor_voters', to='myapp.team')),
                ('robotics_votes', models.ManyToManyField(blank=True, related_name='robotics_voters', to='myapp.team')),
                ('scratch_votes', models.ManyToManyField(blank=True, related_name='scratch_voters', to='myapp.team')),
            ],
        ),
    ]
