# Generated by Django 5.2.4 on 2026-02-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_passcode_uservote_completed_at_uservote_is_complete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingPasscode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voting Passcode',
                'verbose_name_plural': 'Voting Passcode',
            },
        ),
        migrations.RemoveField(
            model_name='uservote',
            name='passcode',
        ),
        migrations.DeleteModel(
            name='Passcode',
        ),
    ]
