# Generated by Django 5.2.4 on 2026-02-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_votingpasscode_remove_uservote_passcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservote',
            name='voter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
