# Generated by Django 5.2.10 on 2026-02-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_uservote_voter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservote',
            name='voter_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
